import kotlin.String
import org.gradle.plugin.use.PluginDependenciesSpec
import org.gradle.plugin.use.PluginDependencySpec

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
object Versions {
    const val android_arch_navigation: String = "1.0.0"

    const val appcompat: String = "1.1.0"

    const val constraintlayout: String = "1.1.3"

    const val core_ktx: String = "1.1.0"

    const val androidx_databinding: String = "3.5.3"

    const val androidx_fragment: String = "1.2.0"

    const val navigation_safe_args_gradle_plugin: String = "2.2.0"

    const val preference: String = "1.1.0"

    const val recyclerview: String = "1.1.0"

    const val androidx_room: String = "2.2.3"

    const val espresso_core: String = "3.2.0"

    const val androidx_test_ext_junit: String = "1.1.1"

    const val androidx_test: String = "1.2.0"

    const val viewpager2: String = "1.0.0"

    const val lottie: String = "3.3.1"

    const val aapt2: String = "3.5.3-5435860"

    const val com_android_tools_build_gradle: String = "3.5.3"

    const val lint_gradle: String = "26.5.3"

    const val com_dorongold_task_tree_gradle_plugin: String = "1.4" // available: "1.5"

    const val stetho: String = "1.5.1"

    const val glide: String = "4.11.0"

    const val oss_licenses_plugin: String = "0.10.1"

    const val play_services_oss_licenses: String = "17.0.0"

    const val material: String = "1.1.0-rc02"

    const val google_services: String = "4.3.3"

    const val threetenabp: String = "1.2.0" // available: "1.2.2"

    const val logger: String = "2.2.0"

    const val ktlint: String = "0.36.0"

    const val library: String = "2.1.4"

    const val de_fayard_buildsrcversions_gradle_plugin: String = "0.4.2" // available: "0.7.0"

    const val tedpermission: String = "2.2.3"

    const val io_fabric_tools_gradle: String = "1.31.2"

    const val io_gitlab_arturbosch_detekt_gradle_plugin: String = "1.0.0" // available: "1.4.0"

    const val junit_junit: String = "4.12" // available: "4.13"

    const val circleindicator: String = "2.1.4"

    const val org_jetbrains_kotlin: String = "1.3.61"

    const val kotlinx_coroutines_android: String = "1.3.3"

    const val org_koin: String = "2.0.1"

    /**
     *
     * See issue 19: How to update Gradle itself?
     * https://github.com/jmfayard/buildSrcVersions/issues/19
     */
    const val gradleLatestVersion: String = "6.1.1"

    const val gradleCurrentVersion: String = "6.1"
}

/**
 * See issue #47: how to update buildSrcVersions itself
 * https://github.com/jmfayard/buildSrcVersions/issues/47
 */
val PluginDependenciesSpec.buildSrcVersions: PluginDependencySpec
    inline get() =
        id("de.fayard.buildSrcVersions").version(Versions.de_fayard_buildsrcversions_gradle_plugin)
